export const IMAGE_MODELS: Record<string, { modalities: string[] }> = {
  "google/gemini-2.5-flash-image": { modalities: ["image", "text"] },
  "black-forest-labs/flux.2-pro": { modalities: ["image"] },
  "black-forest-labs/flux.2-flex": { modalities: ["image"] },
};

export const DEFAULT_IMAGE_MODEL = "black-forest-labs/flux.2-pro";

export interface GenerateImageOptions {
  prompt: string;
  model?: string;
}

export async function generateImage({ prompt, model }: GenerateImageOptions): Promise<Buffer> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) throw new Error("OPENROUTER_API_KEY not configured");

  const useModel = model && IMAGE_MODELS[model] ? model : DEFAULT_IMAGE_MODEL;
  const { modalities } = IMAGE_MODELS[useModel] || IMAGE_MODELS[DEFAULT_IMAGE_MODEL];

  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: useModel,
      messages: [{ role: "user", content: prompt }],
      modalities,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`OpenRouter API error (${useModel}): ${res.status} ${err}`);
  }

  const data = await res.json();
  const images = data.choices?.[0]?.message?.images;
  if (!images || images.length === 0) {
    throw new Error("No image generated by the model");
  }

  const dataUrl: string = images[0].image_url.url;
  const base64 = dataUrl.replace(/^data:image\/\w+;base64,/, "");
  return Buffer.from(base64, "base64");
}
